- name: Create Users & Groups
  hosts: my-pc
  gather_facts: false
  vars:

  become: true
  roles:
    - roles/user_role
    - roles/docker_role
  tasks:








# Now we a going to install docker engine and ssh
    # - name: Add Docker GPG apt Key
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present

    # - name: Add Docker Repository
    #   apt_repository:
    #     repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu focal stable"
    #     state: present


    # - name: Update apt and install docker-ce
    #   apt:
    #     name: docker-ce
    #     state: latest
    #     update_cache: true

    # - name: Install Docker Module for Python
    #   pip:
    #     name: docker

    #  Installation de GnuPG si absent (nécessaire pour apt-key)

    - name: Clean APT cache (fix possible issues)
      command: apt-get clean

    - name: Remove APT lock files (if any)
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
        - /var/lib/apt/lists/lock

    - name: Force update APT cache
      command: apt-get update
      register: apt_update_output
      failed_when: "'Failed to fetch' in apt_update_output.stderr"
      changed_when: false


    - name: Install required dependencies
      apt:
        name: gnupg
        state: present
        update_cache: true





   

# now we are going to install openssh server
    
    - name: install openssh
      apt:
        name: openssh-server
        state: latest
        update_cache: true




