---
# tasks file for user_role


#  create users and groups 

- name: Create Users & Groups (Create group)
  group:
    name: "{{ admin_group }}"
    state: present

- name: Create Users & Groups ( Create Users Task)
  user:
    name: "{{ item }}"
    state: present
    password: "{{ default_user_password | password_hash('sha512', 'A512') }}"
    shell: /bin/bash
    group: "{{ admin_group }}"
  loop:
    - roberto
    - yannick
    - romial
